# Generated by Django 5.1.1 on 2024-09-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('count_albums', models.IntegerField(default=0)),
                ('count_songs', models.IntegerField(default=0)),
                ('count_played', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(null=True)),
                ('count_rated', models.IntegerField(default=0)),
                ('rated_at', models.DateTimeField(null=True)),
                ('rating', models.FloatField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('year', models.IntegerField()),
                ('disc_number', models.IntegerField()),
                ('total_discs', models.IntegerField()),
                ('total_tracks', models.IntegerField()),
                ('count_songs', models.IntegerField(default=0)),
                ('count_played', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(null=True)),
                ('count_rated', models.IntegerField(default=0)),
                ('rated_at', models.DateTimeField(null=True)),
                ('rating', models.FloatField(default=1)),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='albums',
                        to='main.artist',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rel_path', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('track_number', models.IntegerField()),
                ('count_played', models.IntegerField(default=0)),
                ('played_at', models.DateTimeField(null=True)),
                ('rated_at', models.DateTimeField(null=True)),
                ('count_rated', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=1)),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='songs',
                        to='main.album',
                    ),
                ),
                (
                    'artist',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='songs',
                        to='main.artist',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated_at', models.DateTimeField()),
                (
                    'loser',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rating_losers',
                        to='main.song',
                    ),
                ),
                (
                    'winner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rating_winners',
                        to='main.song',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('played_at', models.DateTimeField(null=True)),
                (
                    'song',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='histories',
                        to='main.song',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
