# Generated by Django 5.1.1 on 2024-09-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-played_at']},
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
