# Generated by Django 5.1.1 on 2024-09-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_alter_history_options_alter_album_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='disc_number',
        ),
        migrations.AddField(
            model_name='song',
            name='disc_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
