# Generated by Django 5.1.1 on 2024-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_remove_album_disc_number_song_disc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
