# Generated by Django 5.1.1 on 2024-09-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(
                choices=[
                    ('christian', 'christian'),
                    ('pop and dance', 'pop and dance'),
                    ('soft rock', 'soft rock'),
                    ('hard rock', 'hard rock'),
                    ('metal', 'metal'),
                ],
                default='hard rock',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(
                choices=[
                    ('christian', 'christian'),
                    ('pop and dance', 'pop and dance'),
                    ('soft rock', 'soft rock'),
                    ('hard rock', 'hard rock'),
                    ('metal', 'metal'),
                ],
                default='hard rock',
                max_length=50,
            ),
        ),
    ]
