# Generated by Django 5.1.1 on 2024-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_album_genre_artist_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='disco_at',
            field=models.DateTimeField(null=True),
        ),
    ]
