# Generated by Django 5.1.1 on 2024-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_artist_disco_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'chart',
                    models.CharField(
                        choices=[
                            ('rock', 'rock'),
                            ('alternative', 'alternative'),
                            ('hard rock', 'hard rock'),
                            ('christian', 'christian'),
                            ('gospel', 'gospel'),
                        ],
                        max_length=250,
                    ),
                ),
                ('chart_at', models.DateTimeField()),
                ('pos', models.IntegerField()),
                ('img_src', models.CharField(max_length=250)),
                ('artist_name', models.CharField(max_length=250)),
                ('artist_slug', models.SlugField()),
                ('album_name', models.CharField(max_length=250)),
                ('album_slug', models.SlugField()),
                ('last_week', models.IntegerField(null=True)),
                ('peak_pos', models.IntegerField()),
                ('wks_on_chart', models.IntegerField()),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('chart', 'artist_slug', 'album_slug')},
            },
        ),
    ]
