# Generated by Django 5.1.1 on 2024-09-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0010_billboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billboard',
            options={'ordering': ['chart_at', 'pos']},
        ),
        migrations.AddField(
            model_name='billboard',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='chart',
            field=models.CharField(
                choices=[
                    ('rock', 'rock'),
                    ('alternative', 'alternative'),
                    ('hard rock', 'hard rock'),
                    ('christian', 'christian'),
                ],
                max_length=250,
            ),
        ),
    ]
