# Generated by Django 5.1.1 on 2024-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0012_similar'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='avg_played_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='avg_played_at',
            field=models.DateTimeField(null=True),
        ),
    ]
