# Generated by Django 5.1.1 on 2025-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0013_album_avg_played_at_artist_avg_played_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-played_at'], 'verbose_name_plural': 'Histories'},
        ),
        migrations.AddField(
            model_name='album',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='avg_played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='avg_played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='disco_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='rated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
